import assert from 'node:assert/strict';
import {Match,generateMap,blastCells,rng} from '../public/game/core.mjs';
const names=[];const test=(name,fn)=>{fn();names.push(name);};
function clean(){const g=new Match(9);g.reset(0,'treino');g.map=Array.from({length:15},(_,z)=>Array.from({length:15},(_,x)=>x===0||z===0||x===14||z===14?1:0));g.enemies=[{id:999,x:13,z:13,hp:99,skin:1,cd:10000,think:10000,target:null,invulnerable:0,speed:0,walk:0}];g.events=[];return g;}
test('safe spawns and solid perimeter, 100 seeds',()=>{for(let seed=0;seed<100;seed++){const map=generateMap(rng(seed));assert.equal(map[1][1],0);assert.equal(map[13][13],0);assert.ok(map[0].every(c=>c===1));assert.ok(map[14].every(c=>c===1));}});
test('blast stops at walls and first crate',()=>{const g=clean();g.map[5][6]=1;g.map[7][5]=2;const cells=blastCells(g.map,5,5,5).map(c=>c.join(','));assert.ok(!cells.includes('6,5'));assert.ok(cells.includes('5,7'));assert.ok(!cells.includes('5,8'));});
test('chain explosion removes bombs, destroys crate and scores',()=>{const g=clean();g.map[5][7]=2;g.addBomb(3,5);g.addBomb(5,5);g.explode(g.bombs[0]);assert.equal(g.bombs.length,0);assert.equal(g.map[5][7],0);assert.equal(g.combo,2);assert.equal(g.score,25);});
test('own fire damages once during immunity',()=>{const g=clean();g.player.x=5;g.player.z=5;g.player.invulnerable=0;g.addBomb(5,5);g.explode(g.bombs[0]);for(let n=0;n<10;n++)g.tick(.05);assert.equal(g.player.hp,2);});
test('shield blocks damage',()=>{const g=clean();g.player.x=5;g.player.z=5;g.player.invulnerable=0;g.player.shield=5;g.addBomb(5,5);g.explode(g.bombs[0]);g.tick(.05);assert.equal(g.player.hp,3);});
test('movement cannot pass through walls',()=>{const g=clean();g.map[1][2]=1;for(let n=0;n<120;n++)g.tick(.05,{forward:true});assert.ok(g.player.x<1.3);});
test('three player bombs maximum and refill after explosion',()=>{const g=clean();for(let i=0;i<5;i++){g.player.x=1+i;g.cooldown=0;g.throwBomb(true);}assert.equal(g.bombs.length,3);assert.equal(g.snapshot().bombs,0);g.explode(g.bombs[0]);assert.ok(g.snapshot().bombs>0);});
test('all four specials consume charge and recharge',()=>{for(let c=0;c<4;c++){const g=clean();g.character=c;g.player.hp=2;assert.equal(g.special(),true);assert.equal(g.special(),false);assert.ok(g.player.shield>0);if(c===3)assert.equal(g.player.hp,3);assert.equal(g.specialCharge,0);g.tick(.05);assert.ok(g.specialCharge>0);}});
test('pause freezes all timers and movement',()=>{const g=clean();g.phase='paused';const before=JSON.stringify(g.snapshot());g.tick(.05,{forward:true});assert.equal(JSON.stringify(g.snapshot()),before);});
test('losing and victory are reachable',()=>{const g=clean();g.player.hp=0;g.tick(.05);assert.equal(g.phase,'lost');const h=clean();h.enemies=[];h.tick(.05);assert.equal(h.phase,'won');const k=clean();k.elapsed=180;k.tick(.05);assert.equal(k.phase,'won');});
test('100 autonomous matches stay finite and inside arena',()=>{for(let seed=0;seed<100;seed++){const g=new Match(seed);g.reset(seed%4,'caos');for(let t=0;t<1200;t++){if(t%36===0)g.throwBomb();if(t%99===0)g.special();g.player.yaw+=.003;g.tick(.05,{forward:t%120<60,right:t%180>90});assert.ok(Number.isFinite(g.player.x));assert.ok(g.player.x>.5&&g.player.x<13.5);assert.ok(g.player.z>.5&&g.player.z<13.5);assert.ok(g.bombs.length<40);if(g.phase!=='playing')break;}}});
console.log(JSON.stringify({passed:names.length,checks:names},null,2));
